/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyContent {
  'motivation' : string,
  'hadith' : string,
  'quranReflection' : string,
}
export type Date = bigint;
export interface Fasting { 'note' : [] | [string], 'isFasting' : boolean }
export interface Murojaah {
  'verseStart' : bigint,
  'surah' : string,
  'verseEnd' : bigint,
}
export interface Sedekah {
  'completed' : boolean,
  'paymentLink' : [] | [string],
}
export interface Tahfidz {
  'verseStart' : bigint,
  'surah' : string,
  'verseEnd' : bigint,
}
export interface Task {
  'murojaah' : [] | [Murojaah],
  'tilawah' : [] | [Tilawah],
  'tahfidz' : [] | [Tahfidz],
  'fasting' : [] | [Fasting],
  'sedekah' : [] | [Sedekah],
}
export interface Tilawah {
  'verseStart' : bigint,
  'surah' : string,
  'verseEnd' : bigint,
}
export interface UserProfile {
  'name' : string,
  'isActive' : boolean,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateContent' : ActorMethod<[bigint, DailyContent], undefined>,
  'createOrUpdateTask' : ActorMethod<[Date, Task], undefined>,
  'createOrUpdateTaskForUser' : ActorMethod<[Principal, Date, Task], undefined>,
  'createUser' : ActorMethod<[Principal, UserProfile], undefined>,
  'deactivateUser' : ActorMethod<[Principal], undefined>,
  'deleteContent' : ActorMethod<[bigint], undefined>,
  'getAllUsers' : ActorMethod<[], Array<Principal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContents' : ActorMethod<[], Array<DailyContent>>,
  'getSedekahPaymentLink' : ActorMethod<[], string>,
  'getTask' : ActorMethod<[Date], [] | [Task]>,
  'getTaskForUser' : ActorMethod<[Principal, Date], [] | [Task]>,
  'getTasksInRange' : ActorMethod<[Date, Date], Array<[Date, Task]>>,
  'getTasksInRangeForUser' : ActorMethod<
    [Principal, Date, Date],
    Array<[Date, Task]>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStatistics' : ActorMethod<
    [Principal, Date, Date],
    {
      'tilawahEntries' : bigint,
      'fastingDays' : bigint,
      'tahfidzEntries' : bigint,
      'murojaahEntries' : bigint,
      'sedekahDays' : bigint,
    }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reactivateUser' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setSedekahPaymentLink' : ActorMethod<[string], undefined>,
  'updateUserProfile' : ActorMethod<[Principal, UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];