/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DailyContent = IDL.Record({
  'motivation' : IDL.Text,
  'hadith' : IDL.Text,
  'quranReflection' : IDL.Text,
});
export const Date = IDL.Int;
export const Murojaah = IDL.Record({
  'verseStart' : IDL.Nat,
  'surah' : IDL.Text,
  'verseEnd' : IDL.Nat,
});
export const Tilawah = IDL.Record({
  'verseStart' : IDL.Nat,
  'surah' : IDL.Text,
  'verseEnd' : IDL.Nat,
});
export const Tahfidz = IDL.Record({
  'verseStart' : IDL.Nat,
  'surah' : IDL.Text,
  'verseEnd' : IDL.Nat,
});
export const Fasting = IDL.Record({
  'note' : IDL.Opt(IDL.Text),
  'isFasting' : IDL.Bool,
});
export const Sedekah = IDL.Record({
  'completed' : IDL.Bool,
  'paymentLink' : IDL.Opt(IDL.Text),
});
export const Task = IDL.Record({
  'murojaah' : IDL.Opt(Murojaah),
  'tilawah' : IDL.Opt(Tilawah),
  'tahfidz' : IDL.Opt(Tahfidz),
  'fasting' : IDL.Opt(Fasting),
  'sedekah' : IDL.Opt(Sedekah),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateContent' : IDL.Func([IDL.Int, DailyContent], [], []),
  'createOrUpdateTask' : IDL.Func([Date, Task], [], []),
  'createOrUpdateTaskForUser' : IDL.Func([IDL.Principal, Date, Task], [], []),
  'createUser' : IDL.Func([IDL.Principal, UserProfile], [], []),
  'deactivateUser' : IDL.Func([IDL.Principal], [], []),
  'deleteContent' : IDL.Func([IDL.Int], [], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContents' : IDL.Func([], [IDL.Vec(DailyContent)], ['query']),
  'getSedekahPaymentLink' : IDL.Func([], [IDL.Text], ['query']),
  'getTask' : IDL.Func([Date], [IDL.Opt(Task)], ['query']),
  'getTaskForUser' : IDL.Func(
      [IDL.Principal, Date],
      [IDL.Opt(Task)],
      ['query'],
    ),
  'getTasksInRange' : IDL.Func(
      [Date, Date],
      [IDL.Vec(IDL.Tuple(Date, Task))],
      ['query'],
    ),
  'getTasksInRangeForUser' : IDL.Func(
      [IDL.Principal, Date, Date],
      [IDL.Vec(IDL.Tuple(Date, Task))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStatistics' : IDL.Func(
      [IDL.Principal, Date, Date],
      [
        IDL.Record({
          'tilawahEntries' : IDL.Nat,
          'fastingDays' : IDL.Nat,
          'tahfidzEntries' : IDL.Nat,
          'murojaahEntries' : IDL.Nat,
          'sedekahDays' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reactivateUser' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setSedekahPaymentLink' : IDL.Func([IDL.Text], [], []),
  'updateUserProfile' : IDL.Func([IDL.Principal, UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DailyContent = IDL.Record({
    'motivation' : IDL.Text,
    'hadith' : IDL.Text,
    'quranReflection' : IDL.Text,
  });
  const Date = IDL.Int;
  const Murojaah = IDL.Record({
    'verseStart' : IDL.Nat,
    'surah' : IDL.Text,
    'verseEnd' : IDL.Nat,
  });
  const Tilawah = IDL.Record({
    'verseStart' : IDL.Nat,
    'surah' : IDL.Text,
    'verseEnd' : IDL.Nat,
  });
  const Tahfidz = IDL.Record({
    'verseStart' : IDL.Nat,
    'surah' : IDL.Text,
    'verseEnd' : IDL.Nat,
  });
  const Fasting = IDL.Record({
    'note' : IDL.Opt(IDL.Text),
    'isFasting' : IDL.Bool,
  });
  const Sedekah = IDL.Record({
    'completed' : IDL.Bool,
    'paymentLink' : IDL.Opt(IDL.Text),
  });
  const Task = IDL.Record({
    'murojaah' : IDL.Opt(Murojaah),
    'tilawah' : IDL.Opt(Tilawah),
    'tahfidz' : IDL.Opt(Tahfidz),
    'fasting' : IDL.Opt(Fasting),
    'sedekah' : IDL.Opt(Sedekah),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateContent' : IDL.Func([IDL.Int, DailyContent], [], []),
    'createOrUpdateTask' : IDL.Func([Date, Task], [], []),
    'createOrUpdateTaskForUser' : IDL.Func([IDL.Principal, Date, Task], [], []),
    'createUser' : IDL.Func([IDL.Principal, UserProfile], [], []),
    'deactivateUser' : IDL.Func([IDL.Principal], [], []),
    'deleteContent' : IDL.Func([IDL.Int], [], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContents' : IDL.Func([], [IDL.Vec(DailyContent)], ['query']),
    'getSedekahPaymentLink' : IDL.Func([], [IDL.Text], ['query']),
    'getTask' : IDL.Func([Date], [IDL.Opt(Task)], ['query']),
    'getTaskForUser' : IDL.Func(
        [IDL.Principal, Date],
        [IDL.Opt(Task)],
        ['query'],
      ),
    'getTasksInRange' : IDL.Func(
        [Date, Date],
        [IDL.Vec(IDL.Tuple(Date, Task))],
        ['query'],
      ),
    'getTasksInRangeForUser' : IDL.Func(
        [IDL.Principal, Date, Date],
        [IDL.Vec(IDL.Tuple(Date, Task))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStatistics' : IDL.Func(
        [IDL.Principal, Date, Date],
        [
          IDL.Record({
            'tilawahEntries' : IDL.Nat,
            'fastingDays' : IDL.Nat,
            'tahfidzEntries' : IDL.Nat,
            'murojaahEntries' : IDL.Nat,
            'sedekahDays' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reactivateUser' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setSedekahPaymentLink' : IDL.Func([IDL.Text], [], []),
    'updateUserProfile' : IDL.Func([IDL.Principal, UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };