/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Sedekah {
    completed: boolean;
    paymentLink?: string;
    amount?: bigint;
}
export interface Murojaah {
    verseStart: bigint;
    surah: string;
    verseEnd: bigint;
}
export interface Sholat {
    asr: boolean;
    maghrib: boolean;
    fajr: boolean;
    isha: boolean;
    tarawih: boolean;
    dhuha: boolean;
    dhuhr: boolean;
    qiyamulLail: boolean;
}
export type Date_ = bigint;
export interface Tahfidz {
    verseStart: bigint;
    surah: string;
    verseEnd: bigint;
}
export interface Tilawah {
    verseStart: bigint;
    surah: string;
    verseEnd: bigint;
}
export interface Task {
    murojaah?: Murojaah;
    sholat?: Sholat;
    tilawah?: Tilawah;
    tahfidz?: Tahfidz;
    fasting?: Fasting;
    sedekah?: Sedekah;
}
export interface Fasting {
    note?: string;
    isFasting: boolean;
}
export interface DailyContent {
    motivation: string;
    hadith: string;
    quranReflection: string;
}
export interface UserProfile {
    name: string;
    isActive: boolean;
    email: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createOrUpdateContent(contentType: bigint, content: DailyContent): Promise<void>;
    createOrUpdateTask(date: Date_, task: Task): Promise<void>;
    createOrUpdateTaskForUser(user: Principal, date: Date_, task: Task): Promise<void>;
    createUser(user: Principal, profile: UserProfile): Promise<void>;
    deactivateUser(user: Principal): Promise<void>;
    deleteContent(contentType: bigint): Promise<void>;
    getAllUsers(): Promise<Array<Principal>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContents(): Promise<Array<DailyContent>>;
    getSedekahPaymentLink(): Promise<string>;
    getTask(date: Date_): Promise<Task | null>;
    getTaskForUser(user: Principal, date: Date_): Promise<Task | null>;
    getTasksInRange(startDate: Date_, endDate: Date_): Promise<Array<[Date_, Task]>>;
    getTasksInRangeForUser(user: Principal, startDate: Date_, endDate: Date_): Promise<Array<[Date_, Task]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserStatistics(user: Principal, startDate: Date_, endDate: Date_): Promise<{
        tilawahEntries: bigint;
        fastingDays: bigint;
        tahfidzEntries: bigint;
        murojaahEntries: bigint;
        sholatStats: {
            asr: bigint;
            maghrib: bigint;
            fajr: bigint;
            isha: bigint;
            tarawih: bigint;
            dhuha: bigint;
            dhuhr: bigint;
            qiyamulLail: bigint;
        };
        sedekahDays: bigint;
    }>;
    isCallerAdmin(): Promise<boolean>;
    reactivateUser(user: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setSedekahPaymentLink(link: string): Promise<void>;
    updateUserProfile(user: Principal, profile: UserProfile): Promise<void>;
}
import type { Date as _Date, Fasting as _Fasting, Murojaah as _Murojaah, Sedekah as _Sedekah, Sholat as _Sholat, Tahfidz as _Tahfidz, Task as _Task, Tilawah as _Tilawah, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createOrUpdateContent(arg0: bigint, arg1: DailyContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateContent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateContent(arg0, arg1);
            return result;
        }
    }
    async createOrUpdateTask(arg0: Date_, arg1: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateTask(arg0, to_candid_Task_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateTask(arg0, to_candid_Task_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createOrUpdateTaskForUser(arg0: Principal, arg1: Date_, arg2: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateTaskForUser(arg0, arg1, to_candid_Task_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateTaskForUser(arg0, arg1, to_candid_Task_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createUser(arg0: Principal, arg1: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1);
            return result;
        }
    }
    async deactivateUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateUser(arg0);
            return result;
        }
    }
    async deleteContent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContent(arg0);
            return result;
        }
    }
    async getAllUsers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContents(): Promise<Array<DailyContent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContents();
            return result;
        }
    }
    async getSedekahPaymentLink(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getSedekahPaymentLink();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSedekahPaymentLink();
            return result;
        }
    }
    async getTask(arg0: Date_): Promise<Task | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTaskForUser(arg0: Principal, arg1: Date_): Promise<Task | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaskForUser(arg0, arg1);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaskForUser(arg0, arg1);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksInRange(arg0: Date_, arg1: Date_): Promise<Array<[Date_, Task]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksInRange(arg0, arg1);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksInRange(arg0, arg1);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksInRangeForUser(arg0: Principal, arg1: Date_, arg2: Date_): Promise<Array<[Date_, Task]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksInRangeForUser(arg0, arg1, arg2);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksInRangeForUser(arg0, arg1, arg2);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserStatistics(arg0: Principal, arg1: Date_, arg2: Date_): Promise<{
        tilawahEntries: bigint;
        fastingDays: bigint;
        tahfidzEntries: bigint;
        murojaahEntries: bigint;
        sholatStats: {
            asr: bigint;
            maghrib: bigint;
            fajr: bigint;
            isha: bigint;
            tarawih: bigint;
            dhuha: bigint;
            dhuhr: bigint;
            qiyamulLail: bigint;
        };
        sedekahDays: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserStatistics(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserStatistics(arg0, arg1, arg2);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async reactivateUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reactivateUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reactivateUser(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setSedekahPaymentLink(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSedekahPaymentLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSedekahPaymentLink(arg0);
            return result;
        }
    }
    async updateUserProfile(arg0: Principal, arg1: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Fasting_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Fasting): Fasting {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Sedekah_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sedekah): Sedekah {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Task]): Task | null {
    return value.length === 0 ? null : from_candid_Task_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Murojaah]): Murojaah | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Sholat]): Sholat | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Tilawah]): Tilawah | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Tahfidz]): Tahfidz | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Fasting]): Fasting | null {
    return value.length === 0 ? null : from_candid_Fasting_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Sedekah]): Sedekah | null {
    return value.length === 0 ? null : from_candid_Sedekah_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    murojaah: [] | [_Murojaah];
    sholat: [] | [_Sholat];
    tilawah: [] | [_Tilawah];
    tahfidz: [] | [_Tahfidz];
    fasting: [] | [_Fasting];
    sedekah: [] | [_Sedekah];
}): {
    murojaah?: Murojaah;
    sholat?: Sholat;
    tilawah?: Tilawah;
    tahfidz?: Tahfidz;
    fasting?: Fasting;
    sedekah?: Sedekah;
} {
    return {
        murojaah: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.murojaah)),
        sholat: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.sholat)),
        tilawah: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.tilawah)),
        tahfidz: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.tahfidz)),
        fasting: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.fasting)),
        sedekah: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.sedekah))
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    note: [] | [string];
    isFasting: boolean;
}): {
    note?: string;
    isFasting: boolean;
} {
    return {
        note: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.note)),
        isFasting: value.isFasting
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: boolean;
    paymentLink: [] | [string];
    amount: [] | [bigint];
}): {
    completed: boolean;
    paymentLink?: string;
    amount?: bigint;
} {
    return {
        completed: value.completed,
        paymentLink: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.paymentLink)),
        amount: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.amount))
    };
}
function from_candid_tuple_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Date, _Task]): [Date_, Task] {
    return [
        value[0],
        from_candid_Task_n13(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Date, _Task]>): Array<[Date_, Task]> {
    return value.map((x)=>from_candid_tuple_n28(_uploadFile, _downloadFile, x));
}
function to_candid_Fasting_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Fasting): _Fasting {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Sedekah_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sedekah): _Sedekah {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Task_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Task): _Task {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    murojaah?: Murojaah;
    sholat?: Sholat;
    tilawah?: Tilawah;
    tahfidz?: Tahfidz;
    fasting?: Fasting;
    sedekah?: Sedekah;
}): {
    murojaah: [] | [_Murojaah];
    sholat: [] | [_Sholat];
    tilawah: [] | [_Tilawah];
    tahfidz: [] | [_Tahfidz];
    fasting: [] | [_Fasting];
    sedekah: [] | [_Sedekah];
} {
    return {
        murojaah: value.murojaah ? candid_some(value.murojaah) : candid_none(),
        sholat: value.sholat ? candid_some(value.sholat) : candid_none(),
        tilawah: value.tilawah ? candid_some(value.tilawah) : candid_none(),
        tahfidz: value.tahfidz ? candid_some(value.tahfidz) : candid_none(),
        fasting: value.fasting ? candid_some(to_candid_Fasting_n5(_uploadFile, _downloadFile, value.fasting)) : candid_none(),
        sedekah: value.sedekah ? candid_some(to_candid_Sedekah_n7(_uploadFile, _downloadFile, value.sedekah)) : candid_none()
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    note?: string;
    isFasting: boolean;
}): {
    note: [] | [string];
    isFasting: boolean;
} {
    return {
        note: value.note ? candid_some(value.note) : candid_none(),
        isFasting: value.isFasting
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: boolean;
    paymentLink?: string;
    amount?: bigint;
}): {
    completed: boolean;
    paymentLink: [] | [string];
    amount: [] | [bigint];
} {
    return {
        completed: value.completed,
        paymentLink: value.paymentLink ? candid_some(value.paymentLink) : candid_none(),
        amount: value.amount ? candid_some(value.amount) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
